# CodeRabbit Configuration File
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
reviews:
  # Prevent CodeRabbit from updating pipeline status
  commit_status: false
